# Generated by Django 4.1.5 on 2023-06-05 20:26

import Main.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Custom_image", models.ImageField(upload_to="Media/Owner/OwnerPic")),
                ("name", models.CharField(max_length=100)),
                ("Age", models.IntegerField()),
                ("Resume_url", models.CharField(max_length=250)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "project_link",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "source_code_link_github",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "Main_image",
                    models.ImageField(upload_to=Main.models.MainImageFilePathProject),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("Project", models.ManyToManyField(to="Main.project")),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=Main.models.ImageFilePathProject),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "Project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="Main.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Phone_number", models.CharField(max_length=11)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Main.owner"
                    ),
                ),
            ],
        ),
    ]
