# Generated by Django 4.1.5 on 2023-06-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="image",
            unique_together={("image_id", "Project")},
        ),
    ]
