# Generated by Django 4.1.5 on 2023-06-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0002_image_image_id_alter_image_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="job_title",
            field=models.CharField(max_length=80, null=True),
        ),
    ]
