# Generated by Django 4.1.5 on 2023-06-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0003_owner_job_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="job_title",
            field=models.CharField(max_length=80),
        ),
    ]
